### ISSUE TITLE
Unable to resolve module expo-modules-core / TypeError: undefined is not an object  (evaluating '_expoModulesCore.NativeModulesProxy.ExpoSplashScreen')

### ISSUE THREAD

**Issue by AlanDellonSchwartzman** [creativetimofficial/argon-react-native#38]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [y] I am running the latest version
- [y] I checked the documentation and found no answer
- [y] I checked to make sure that this issue has not already been filed
- [y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

run expo start --android and the app starts correctly with no errors

# Current Behavior

run expo start --android and show the error in finallized build

Unable to resolve module expo-modules-core from /Users/MYNAMES/Desktop/argon-pro-react-native-v1.6.0/node_modules/expo-splash-screen/build/SplashScreen.js: expo-modules-core could not be found within the project.

# Failure Information (for bugs)

Unable to resolve module expo-modules-core from /Users/MYNAMES/Desktop/argon-pro-react-native-v1.6.0/node_modules/expo-splash-screen/build/SplashScreen.js: expo-modules-core could not be found within the project.

variant bug: 

Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:200:6 in runApplication

TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExpoSplashScreen')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. clone repo
2. run yarn
3. run yarn start --android

## Context

* Device: Emulator Pixel 4 android 10 (Sdk 29)
* Operating System: Ubuntu 20.04 LTS

## Failure Logs

Unable to start your application. Please refer to https://expo.fyi/no-registered-application for more information.
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:200:6 in runApplication

TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExpoSplashScreen')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

**Comment by AlanDellonSchwartzman** [comment]
the solution is in this PR #39
