### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by gitsmitty** [creativetimofficial/argon-react-native#46]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Running npm install from root directory should work without errors. Vulnerabilities acceptable.

# Current Behavior

Current behavior produces error when running npm install.

# Failure Information (for bugs)

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: argon-react-native@1.8.0
npm ERR! Found: @react-navigation/native@6.1.7
npm ERR! node_modules/@react-navigation/native
npm ERR!   @react-navigation/native@"^6.0.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @react-navigation/native@"^5.0.5" from @react-navigation/compat@5.3.20
npm ERR! node_modules/@react-navigation/compat
npm ERR!   @react-navigation/compat@"^5.1.25" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

## Steps to Reproduce

git clone https://github.com/creativetimofficial/argon-react-native.git argon-react-native
cd argon-react-native
npm install

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Laptop
Windows 10 Pro
Running commands from powershell

## Failure Logs

0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@9.8.0
2 info using node@v16.17.1
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\src\codeflume\viola\argon-react-native\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\mrsmi\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\mrsmi\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 10ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm install
22 verbose argv "install"
23 timing npm:load:setTitle Completed in 0ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:C:\Users\mrsmi\AppData\Local\npm-cache\_logs\2023-07-19T00_40_16_451Z-
26 verbose logfile C:\Users\mrsmi\AppData\Local\npm-cache\_logs\2023-07-19T00_40_16_451Z-debug-0.log
27 timing npm:load:logFile Completed in 19ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 69ms
31 timing arborist:ctor Completed in 1ms
32 timing arborist:ctor Completed in 0ms
33 silly logfile start cleaning logs, removing 2 files
34 timing idealTree:init Completed in 16ms
35 timing idealTree:userRequests Completed in 0ms
36 silly idealTree buildDeps
37 silly fetch manifest @react-native-masked-view/masked-view@0.2.6
38 silly logfile done cleaning log files
39 http fetch GET 200 https://registry.npmjs.org/@react-native-masked-view%2fmasked-view 278ms (cache miss)
40 silly fetch manifest react@17.0.2
41 http fetch GET 200 https://registry.npmjs.org/react 77ms (cache revalidated)
42 silly fetch manifest react-native@0.68.2
43 http fetch GET 200 https://registry.npmjs.org/react-native 341ms (cache updated)
44 silly fetch manifest @react-navigation/bottom-tabs@^6.3.1
45 http fetch GET 200 https://registry.npmjs.org/@react-navigation%2fbottom-tabs 99ms (cache miss)
46 silly fetch manifest @react-navigation/native@^6.0.10
47 http fetch GET 200 https://registry.npmjs.org/@react-navigation%2fnative 91ms (cache revalidated)
48 silly fetch manifest react-native-safe-area-context@4.2.4
49 http fetch GET 200 https://registry.npmjs.org/react-native-safe-area-context 72ms (cache revalidated)
50 silly fetch manifest react-native-screens@~3.11.1
51 http fetch GET 200 https://registry.npmjs.org/react-native-screens 75ms (cache revalidated)
52 silly fetch manifest @react-navigation/compat@^5.1.25
53 http fetch GET 200 https://registry.npmjs.org/@react-navigation%2fcompat 383ms (cache miss)
54 silly fetch manifest @react-navigation/native@^5.0.5
55 timing idealTree Completed in 1551ms
56 timing command:install Completed in 1557ms
57 verbose stack Error: unable to resolve dependency tree
57 verbose stack     at Arborist.#failPeerConflict (C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1376:25)
57 verbose stack     at Arborist.#loadPeerSet (C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1342:33)
57 verbose stack     at async Arborist.#buildDepStep (C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:917:11)
57 verbose stack     at async Arborist.buildIdealTree (C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:196:7)
57 verbose stack     at async Promise.all (index 1)
57 verbose stack     at async Arborist.reify (C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
57 verbose stack     at async Install.exec (C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:149:5)
57 verbose stack     at async module.exports (C:\Users\mrsmi\AppData\Roaming\npm\node_modules\npm\lib\cli-entry.js:61:5)
58 verbose cwd C:\src\codeflume\viola\argon-react-native
59 verbose Windows_NT 10.0.22621
60 verbose node v16.17.1
61 verbose npm  v9.8.0
62 error code ERESOLVE
63 error ERESOLVE unable to resolve dependency tree
64 error
65 error While resolving: argon-react-native@1.8.0
65 error Found: @react-navigation/native@6.1.7
65 error node_modules/@react-navigation/native
65 error   @react-navigation/native@"^6.0.10" from the root project
65 error
65 error Could not resolve dependency:
65 error peer @react-navigation/native@"^5.0.5" from @react-navigation/compat@5.3.20
65 error node_modules/@react-navigation/compat
65 error   @react-navigation/compat@"^5.1.25" from the root project
65 error
65 error Fix the upstream dependency conflict, or retry
65 error this command with --force or --legacy-peer-deps
65 error to accept an incorrect (and potentially broken) dependency resolution.
66 error
66 error
66 error For a full report see:
66 error C:\Users\mrsmi\AppData\Local\npm-cache\_logs\2023-07-19T00_40_16_451Z-eresolve-report.txt
67 verbose exit 1
68 timing npm Completed in 1909ms
69 verbose unfinished npm timer reify 1689727216791
70 verbose unfinished npm timer reify:loadTrees 1689727216794
71 verbose unfinished npm timer idealTree:buildDeps 1689727216811
72 verbose unfinished npm timer idealTree:#root 1689727216811
73 verbose code 1

**Comment by gitsmitty** [comment]
@dragosct Can you help here sir? Was referred by Creative Tim support. I'm buying all these templates up but need to get approval once I have them running please. Thank you for your help in advance.

**Comment by pollog09** [comment]
I am also facing the same problem with this template, I am unable to make it work. without removing the problematic dependencies.

@react-navigation/compat
@react-navigation/native

**Comment by Priyanshu-0301** [comment]
i have checked all the possibilities and I found that it is most likely due to you have put package-lock.json file in .gitignore file and while after cloning the repo running npm install command terminal is not able to giure about some information about dependencies that is stored in package-lock.json. but this is a problem no one can tell for sure what the exact error is so you can try this out to solve this bug, exclude package-lock.json from .gitignore then push it to github

**Comment by KarynaKhatkhokhu** [comment]
I have a similar setup (Windows 11 + powershell) and exactly the same problem. Will update if I manage to solve it.
